version: "3.8"

services:
  cloudlunacy-agent:
    container_name: cloudlunacy-agent
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3005
      - HEALTH_PORT=9000
    ports:
      - "3006:3006"
      - "9000:9000"
    env_file:
      - ".env.dev"
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
    networks:
      - cloudlunacy-network
    restart: unless-stopped

  mongodb:
    container_name: mongodb-agent
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - mongodb_data:/data/db
    networks:
      - cloudlunacy-network
    restart: unless-stopped

networks:
  cloudlunacy-network:
    driver: bridge

volumes:
  mongodb_data:
