FROM node:18-alpine

# Install necessary packages
RUN apk add --no-cache wget curl bash nano docker docker-compose

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g nodemon

# Copy the rest of the application code
COPY . .

# Expose ports
EXPOSE 3006 9000

# Start the application directly
CMD sh -c "node health-server.js & nodemon agent.js" 