name: Create Release

on:
  push:
    tags:
      - "v*" # Triggers on tags starting with 'v'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to update releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for branches and tags
          path: "." # Check out into the current directory

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Verify Scripts Directory
        run: ls -la scripts/

      - name: Set Execute Permissions
        run: chmod +x scripts/install-agent.sh

      - name: Generate SHA256 Checksum
        run: |
          cd scripts
          sha256sum install-agent.sh > install-agent.sh.sha256

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release
            - Describe your changes here.
          artifacts: |
            scripts/install-agent.sh
            scripts/install-agent.sh.sha256
          draft: false
          prerelease: false
